version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mounts the project directory into the container for development.
      # For production, you might want to remove this or make it read-only.
      - .:/app
      # Exclude node_modules from being overwritten by the host's node_modules
      - /app/node_modules
      # Exclude the dist folder from being overwritten if you build outside and copy
      - /app/dist
    environment:
      # Example: Set environment variables for your application
      # NODE_ENV: development
      # VITE_API_URL: http://localhost:3000
      # Add any other environment variables your application needs
      HOST: "0.0.0.0"
      PORT: "8080"
