// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://regozquxnqhcnziyyuvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZ296cXV4bnFoY256aXl5dXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzUzMDksImV4cCI6MjA2Mjg1MTMwOX0.-BRPhPctZhiKO-vXdDAHFJkBcJANjc3c78iYmQVADVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);